
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tempuri;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2013-10-28T10:36:15.678+01:00
 * Generated source version: 2.6.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "AdminService",
                      portName = "WcfAdminSoapService",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "https://partnerweb.sveaekonomi.se/WebPayAdminService/AdminService.svc?WSDL",
                      endpointInterface = "org.tempuri.IAdminService")
                      
public class IAdminServiceImpl implements IAdminService {

    private static final Logger LOG = Logger.getLogger(IAdminServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#cancelOrder(org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderResponse cancelOrder(org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRequest request) { 
        LOG.info("Executing operation cancelOrder");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getRegressionReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetRegressionReportRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetRegressionReportResponse getRegressionReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetRegressionReportRequest request) { 
        LOG.info("Executing operation getRegressionReport");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetRegressionReportResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getAccountingReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetAccountingReportRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetAccountingReportResponse getAccountingReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetAccountingReportRequest request) { 
        LOG.info("Executing operation getAccountingReport");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetAccountingReportResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#updateOrder(org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderResponse updateOrder(org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRequest request) { 
        LOG.info("Executing operation updateOrder");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#deliverPartial(org.datacontract.schemas._2004._07.dataobjects_admin.PartialDeliveryRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse deliverPartial(org.datacontract.schemas._2004._07.dataobjects_admin.PartialDeliveryRequest request) { 
        LOG.info("Executing operation deliverPartial");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getInvoices(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesResponse getInvoices(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesRequest request) { 
        LOG.info("Executing operation getInvoices");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#deliverOrders(org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse deliverOrders(org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryRequest request) { 
        LOG.info("Executing operation deliverOrders");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getOrderPdfLink(org.datacontract.schemas._2004._07.dataobjects_admin.GetOrderPdfLinkRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.PdfLinkResponse getOrderPdfLink(org.datacontract.schemas._2004._07.dataobjects_admin.GetOrderPdfLinkRequest request) { 
        LOG.info("Executing operation getOrderPdfLink");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.PdfLinkResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getInvoiceReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceReportRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceReportResponse getInvoiceReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceReportRequest request) { 
        LOG.info("Executing operation getInvoiceReport");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceReportResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getSumOfPaymentPlanAmount(org.datacontract.schemas._2004._07.dataobjects_admin.SumOfPaymentPlanAmountRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse getSumOfPaymentPlanAmount(org.datacontract.schemas._2004._07.dataobjects_admin.SumOfPaymentPlanAmountRequest request) { 
        LOG.info("Executing operation getSumOfPaymentPlanAmount");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getSumOfInvoiceAmount(org.datacontract.schemas._2004._07.dataobjects_admin.SumOfInvoiceAmountRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse getSumOfInvoiceAmount(org.datacontract.schemas._2004._07.dataobjects_admin.SumOfInvoiceAmountRequest request) { 
        LOG.info("Executing operation getSumOfInvoiceAmount");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#updateOrderRows(org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRowsRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRowsResponse updateOrderRows(org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRowsRequest request) { 
        LOG.info("Executing operation updateOrderRows");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRowsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#creditInvoiceRows(org.datacontract.schemas._2004._07.dataobjects_admin.CreditInvoiceRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse creditInvoiceRows(org.datacontract.schemas._2004._07.dataobjects_admin.CreditInvoiceRequest request) { 
        LOG.info("Executing operation creditInvoiceRows");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#searchOrders(org.datacontract.schemas._2004._07.dataobjects_admin.SearchOrdersRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.SearchOrdersResponse searchOrders(org.datacontract.schemas._2004._07.dataobjects_admin.SearchOrdersRequest request) { 
        LOG.info("Executing operation searchOrders");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.SearchOrdersResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#releasePendingOrder(org.datacontract.schemas._2004._07.dataobjects_admin.ReleasePendingRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.ReleasePendingResponse releasePendingOrder(org.datacontract.schemas._2004._07.dataobjects_admin.ReleasePendingRequest request) { 
        LOG.info("Executing operation releasePendingOrder");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.ReleasePendingResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getOrders(org.datacontract.schemas._2004._07.dataobjects_admin.GetOrdersRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetOrdersResponse getOrders(org.datacontract.schemas._2004._07.dataobjects_admin.GetOrdersRequest request) { 
        LOG.info("Executing operation getOrders");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetOrdersResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getSumOfOrderAmount(org.datacontract.schemas._2004._07.dataobjects_admin.SumOfOrderAmountRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse getSumOfOrderAmount(org.datacontract.schemas._2004._07.dataobjects_admin.SumOfOrderAmountRequest request) { 
        LOG.info("Executing operation getSumOfOrderAmount");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#cancelOrderRows(org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRowsRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRowsResponse cancelOrderRows(org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRowsRequest request) { 
        LOG.info("Executing operation cancelOrderRows");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRowsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#createOrder(org.datacontract.schemas._2004._07.dataobjects_admin.CreateOrderRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.CreateOrderResponse createOrder(org.datacontract.schemas._2004._07.dataobjects_admin.CreateOrderRequest request) { 
        LOG.info("Executing operation createOrder");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.CreateOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getFinancialReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetFinancialReportRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetFinancialReportResponse getFinancialReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetFinancialReportRequest request) { 
        LOG.info("Executing operation getFinancialReport");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetFinancialReportResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#changeInvoiceDueDate(org.datacontract.schemas._2004._07.dataobjects_admin.ChangeInvoiceDueDateRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.ChangeInvoiceDueDateResponse changeInvoiceDueDate(org.datacontract.schemas._2004._07.dataobjects_admin.ChangeInvoiceDueDateRequest request) { 
        LOG.info("Executing operation changeInvoiceDueDate");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.ChangeInvoiceDueDateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getInvoicesWithChangedDueDate(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesWithChangedDueDateRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesWithChangedDueDateResponse getInvoicesWithChangedDueDate(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesWithChangedDueDateRequest request) { 
        LOG.info("Executing operation getInvoicesWithChangedDueDate");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesWithChangedDueDateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#searchInvoices(org.datacontract.schemas._2004._07.dataobjects_admin.SearchInvoicesRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.SearchInvoicesResponse searchInvoices(org.datacontract.schemas._2004._07.dataobjects_admin.SearchInvoicesRequest request) { 
        LOG.info("Executing operation searchInvoices");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.SearchInvoicesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getPaymentPlanReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetPaymentPlanReportRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetPaymentPlanReportResponse getPaymentPlanReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetPaymentPlanReportRequest request) { 
        LOG.info("Executing operation getPaymentPlanReport");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetPaymentPlanReportResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#searchPaymentPlans(org.datacontract.schemas._2004._07.dataobjects_admin.SearchPaymentPlansRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.SearchPaymentPlansResponse searchPaymentPlans(org.datacontract.schemas._2004._07.dataobjects_admin.SearchPaymentPlansRequest request) { 
        LOG.info("Executing operation searchPaymentPlans");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.SearchPaymentPlansResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getInvoiceJournalReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceJournalReportRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceJournalReportResponse getInvoiceJournalReport(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceJournalReportRequest request) { 
        LOG.info("Executing operation getInvoiceJournalReport");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceJournalReportResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#approveInvoice(org.datacontract.schemas._2004._07.dataobjects_admin.ApproveInvoiceRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.ApproveInvoiceResponse approveInvoice(org.datacontract.schemas._2004._07.dataobjects_admin.ApproveInvoiceRequest request) { 
        LOG.info("Executing operation approveInvoice");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.ApproveInvoiceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#getInvoicePdfLink(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicePdfLinkRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.PdfLinkResponse getInvoicePdfLink(org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicePdfLinkRequest request) { 
        LOG.info("Executing operation getInvoicePdfLink");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.PdfLinkResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IAdminService#addOrderRows(org.datacontract.schemas._2004._07.dataobjects_admin.AddOrderRowsRequest  request )*
     */
    public org.datacontract.schemas._2004._07.dataobjects_admin.AddOrderRowsResponse addOrderRows(org.datacontract.schemas._2004._07.dataobjects_admin.AddOrderRowsRequest request) { 
        LOG.info("Executing operation addOrderRows");
        System.out.println(request);
        try {
            org.datacontract.schemas._2004._07.dataobjects_admin.AddOrderRowsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
