
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-27T15:04:25.886+01:00
 * Generated source version: 2.7.8
 * 
 */
public final class IAdminService_AdminSoapService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "AdminService");

    private IAdminService_AdminSoapService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AdminService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AdminService ss = new AdminService(wsdlURL, SERVICE_NAME);
        IAdminService port = ss.getAdminSoapService();  
        
        {
        System.out.println("Invoking cancelOrder...");
        org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRequest _cancelOrder_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderResponse _cancelOrder__return = port.cancelOrder(_cancelOrder_request);
        System.out.println("cancelOrder.result=" + _cancelOrder__return);


        }
        {
        System.out.println("Invoking getRegressionReport...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetRegressionReportRequest _getRegressionReport_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetRegressionReportResponse _getRegressionReport__return = port.getRegressionReport(_getRegressionReport_request);
        System.out.println("getRegressionReport.result=" + _getRegressionReport__return);


        }
        {
        System.out.println("Invoking getAccountingReport...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetAccountingReportRequest _getAccountingReport_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetAccountingReportResponse _getAccountingReport__return = port.getAccountingReport(_getAccountingReport_request);
        System.out.println("getAccountingReport.result=" + _getAccountingReport__return);


        }
        {
        System.out.println("Invoking updateOrder...");
        org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRequest _updateOrder_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderResponse _updateOrder__return = port.updateOrder(_updateOrder_request);
        System.out.println("updateOrder.result=" + _updateOrder__return);


        }
        {
        System.out.println("Invoking deliverPartial...");
        org.datacontract.schemas._2004._07.dataobjects_admin.PartialDeliveryRequest _deliverPartial_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse _deliverPartial__return = port.deliverPartial(_deliverPartial_request);
        System.out.println("deliverPartial.result=" + _deliverPartial__return);


        }
        {
        System.out.println("Invoking getInvoices...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesRequest _getInvoices_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesResponse _getInvoices__return = port.getInvoices(_getInvoices_request);
        System.out.println("getInvoices.result=" + _getInvoices__return);


        }
        {
        System.out.println("Invoking deliverOrders...");
        org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryRequest _deliverOrders_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse _deliverOrders__return = port.deliverOrders(_deliverOrders_request);
        System.out.println("deliverOrders.result=" + _deliverOrders__return);


        }
        {
        System.out.println("Invoking getOrderPdfLink...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetOrderPdfLinkRequest _getOrderPdfLink_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.PdfLinkResponse _getOrderPdfLink__return = port.getOrderPdfLink(_getOrderPdfLink_request);
        System.out.println("getOrderPdfLink.result=" + _getOrderPdfLink__return);


        }
        {
        System.out.println("Invoking getInvoiceReport...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceReportRequest _getInvoiceReport_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceReportResponse _getInvoiceReport__return = port.getInvoiceReport(_getInvoiceReport_request);
        System.out.println("getInvoiceReport.result=" + _getInvoiceReport__return);


        }
        {
        System.out.println("Invoking getSumOfPaymentPlanAmount...");
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfPaymentPlanAmountRequest _getSumOfPaymentPlanAmount_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse _getSumOfPaymentPlanAmount__return = port.getSumOfPaymentPlanAmount(_getSumOfPaymentPlanAmount_request);
        System.out.println("getSumOfPaymentPlanAmount.result=" + _getSumOfPaymentPlanAmount__return);


        }
        {
        System.out.println("Invoking getSumOfInvoiceAmount...");
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfInvoiceAmountRequest _getSumOfInvoiceAmount_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse _getSumOfInvoiceAmount__return = port.getSumOfInvoiceAmount(_getSumOfInvoiceAmount_request);
        System.out.println("getSumOfInvoiceAmount.result=" + _getSumOfInvoiceAmount__return);


        }
        {
        System.out.println("Invoking updateOrderRows...");
        org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRowsRequest _updateOrderRows_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRowsResponse _updateOrderRows__return = port.updateOrderRows(_updateOrderRows_request);
        System.out.println("updateOrderRows.result=" + _updateOrderRows__return);


        }
        {
        System.out.println("Invoking creditInvoiceRows...");
        org.datacontract.schemas._2004._07.dataobjects_admin.CreditInvoiceRequest _creditInvoiceRows_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse _creditInvoiceRows__return = port.creditInvoiceRows(_creditInvoiceRows_request);
        System.out.println("creditInvoiceRows.result=" + _creditInvoiceRows__return);


        }
        {
        System.out.println("Invoking searchOrders...");
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchOrdersRequest _searchOrders_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchOrdersResponse _searchOrders__return = port.searchOrders(_searchOrders_request);
        System.out.println("searchOrders.result=" + _searchOrders__return);


        }
        {
        System.out.println("Invoking releasePendingOrder...");
        org.datacontract.schemas._2004._07.dataobjects_admin.ReleasePendingRequest _releasePendingOrder_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.ReleasePendingResponse _releasePendingOrder__return = port.releasePendingOrder(_releasePendingOrder_request);
        System.out.println("releasePendingOrder.result=" + _releasePendingOrder__return);


        }
        {
        System.out.println("Invoking getOrders...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetOrdersRequest _getOrders_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetOrdersResponse _getOrders__return = port.getOrders(_getOrders_request);
        System.out.println("getOrders.result=" + _getOrders__return);


        }
        {
        System.out.println("Invoking getSumOfOrderAmount...");
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfOrderAmountRequest _getSumOfOrderAmount_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse _getSumOfOrderAmount__return = port.getSumOfOrderAmount(_getSumOfOrderAmount_request);
        System.out.println("getSumOfOrderAmount.result=" + _getSumOfOrderAmount__return);


        }
        {
        System.out.println("Invoking cancelOrderRows...");
        org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRowsRequest _cancelOrderRows_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRowsResponse _cancelOrderRows__return = port.cancelOrderRows(_cancelOrderRows_request);
        System.out.println("cancelOrderRows.result=" + _cancelOrderRows__return);


        }
        {
        System.out.println("Invoking createOrder...");
        org.datacontract.schemas._2004._07.dataobjects_admin.CreateOrderRequest _createOrder_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.CreateOrderResponse _createOrder__return = port.createOrder(_createOrder_request);
        System.out.println("createOrder.result=" + _createOrder__return);


        }
        {
        System.out.println("Invoking getFinancialReport...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetFinancialReportRequest _getFinancialReport_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetFinancialReportResponse _getFinancialReport__return = port.getFinancialReport(_getFinancialReport_request);
        System.out.println("getFinancialReport.result=" + _getFinancialReport__return);


        }
        {
        System.out.println("Invoking changeInvoiceDueDate...");
        org.datacontract.schemas._2004._07.dataobjects_admin.ChangeInvoiceDueDateRequest _changeInvoiceDueDate_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.ChangeInvoiceDueDateResponse _changeInvoiceDueDate__return = port.changeInvoiceDueDate(_changeInvoiceDueDate_request);
        System.out.println("changeInvoiceDueDate.result=" + _changeInvoiceDueDate__return);


        }
        {
        System.out.println("Invoking getInvoicesWithChangedDueDate...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesWithChangedDueDateRequest _getInvoicesWithChangedDueDate_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesWithChangedDueDateResponse _getInvoicesWithChangedDueDate__return = port.getInvoicesWithChangedDueDate(_getInvoicesWithChangedDueDate_request);
        System.out.println("getInvoicesWithChangedDueDate.result=" + _getInvoicesWithChangedDueDate__return);


        }
        {
        System.out.println("Invoking searchInvoices...");
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchInvoicesRequest _searchInvoices_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchInvoicesResponse _searchInvoices__return = port.searchInvoices(_searchInvoices_request);
        System.out.println("searchInvoices.result=" + _searchInvoices__return);


        }
        {
        System.out.println("Invoking getPaymentPlanReport...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetPaymentPlanReportRequest _getPaymentPlanReport_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetPaymentPlanReportResponse _getPaymentPlanReport__return = port.getPaymentPlanReport(_getPaymentPlanReport_request);
        System.out.println("getPaymentPlanReport.result=" + _getPaymentPlanReport__return);


        }
        {
        System.out.println("Invoking searchPaymentPlans...");
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchPaymentPlansRequest _searchPaymentPlans_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchPaymentPlansResponse _searchPaymentPlans__return = port.searchPaymentPlans(_searchPaymentPlans_request);
        System.out.println("searchPaymentPlans.result=" + _searchPaymentPlans__return);


        }
        {
        System.out.println("Invoking getInvoiceJournalReport...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceJournalReportRequest _getInvoiceJournalReport_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceJournalReportResponse _getInvoiceJournalReport__return = port.getInvoiceJournalReport(_getInvoiceJournalReport_request);
        System.out.println("getInvoiceJournalReport.result=" + _getInvoiceJournalReport__return);


        }
        {
        System.out.println("Invoking approveInvoice...");
        org.datacontract.schemas._2004._07.dataobjects_admin.ApproveInvoiceRequest _approveInvoice_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.ApproveInvoiceResponse _approveInvoice__return = port.approveInvoice(_approveInvoice_request);
        System.out.println("approveInvoice.result=" + _approveInvoice__return);


        }
        {
        System.out.println("Invoking getInvoicePdfLink...");
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicePdfLinkRequest _getInvoicePdfLink_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.PdfLinkResponse _getInvoicePdfLink__return = port.getInvoicePdfLink(_getInvoicePdfLink_request);
        System.out.println("getInvoicePdfLink.result=" + _getInvoicePdfLink__return);


        }
        {
        System.out.println("Invoking addOrderRows...");
        org.datacontract.schemas._2004._07.dataobjects_admin.AddOrderRowsRequest _addOrderRows_request = null;
        org.datacontract.schemas._2004._07.dataobjects_admin.AddOrderRowsResponse _addOrderRows__return = port.addOrderRows(_addOrderRows_request);
        System.out.println("addOrderRows.result=" + _addOrderRows__return);


        }

        System.exit(0);
    }

}
