package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-27T15:04:25.908+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IAdminService")
@XmlSeeAlso({ObjectFactory.class, org.datacontract.schemas._2004._07.dataobjects.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.dataobjects_webservice.ObjectFactory.class, org.datacontract.schemas._2004._07.dataobjects_admin.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IAdminService {

    @WebResult(name = "CancelOrderResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/CancelOrder", output = "http://tempuri.org/IAdminService/CancelOrderResponse")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelOrder")
    @WebMethod(operationName = "CancelOrder", action = "http://tempuri.org/IAdminService/CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelOrderResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderResponse cancelOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRequest request
    );

    @WebResult(name = "GetRegressionReportResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetRegressionReport", output = "http://tempuri.org/IAdminService/GetRegressionReportResponse")
    @RequestWrapper(localName = "GetRegressionReport", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegressionReport")
    @WebMethod(operationName = "GetRegressionReport", action = "http://tempuri.org/IAdminService/GetRegressionReport")
    @ResponseWrapper(localName = "GetRegressionReportResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegressionReportResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetRegressionReportResponse getRegressionReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetRegressionReportRequest request
    );

    @WebResult(name = "GetAccountingReportResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetAccountingReport", output = "http://tempuri.org/IAdminService/GetAccountingReportResponse")
    @RequestWrapper(localName = "GetAccountingReport", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccountingReport")
    @WebMethod(operationName = "GetAccountingReport", action = "http://tempuri.org/IAdminService/GetAccountingReport")
    @ResponseWrapper(localName = "GetAccountingReportResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccountingReportResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetAccountingReportResponse getAccountingReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetAccountingReportRequest request
    );

    @WebResult(name = "UpdateOrderResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/UpdateOrder", output = "http://tempuri.org/IAdminService/UpdateOrderResponse")
    @RequestWrapper(localName = "UpdateOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOrder")
    @WebMethod(operationName = "UpdateOrder", action = "http://tempuri.org/IAdminService/UpdateOrder")
    @ResponseWrapper(localName = "UpdateOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOrderResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderResponse updateOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRequest request
    );

    @WebResult(name = "DeliverPartialResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/DeliverPartial", output = "http://tempuri.org/IAdminService/DeliverPartialResponse")
    @RequestWrapper(localName = "DeliverPartial", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeliverPartial")
    @WebMethod(operationName = "DeliverPartial", action = "http://tempuri.org/IAdminService/DeliverPartial")
    @ResponseWrapper(localName = "DeliverPartialResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeliverPartialResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse deliverPartial(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.PartialDeliveryRequest request
    );

    @WebResult(name = "GetInvoicesResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoices", output = "http://tempuri.org/IAdminService/GetInvoicesResponse")
    @RequestWrapper(localName = "GetInvoices", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoices")
    @WebMethod(operationName = "GetInvoices", action = "http://tempuri.org/IAdminService/GetInvoices")
    @ResponseWrapper(localName = "GetInvoicesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoicesResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesResponse getInvoices(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesRequest request
    );

    @WebResult(name = "DeliverOrdersResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/DeliverOrders", output = "http://tempuri.org/IAdminService/DeliverOrdersResponse")
    @RequestWrapper(localName = "DeliverOrders", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeliverOrders")
    @WebMethod(operationName = "DeliverOrders", action = "http://tempuri.org/IAdminService/DeliverOrders")
    @ResponseWrapper(localName = "DeliverOrdersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeliverOrdersResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse deliverOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryRequest request
    );

    @WebResult(name = "GetOrderPdfLinkResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetOrderPdfLink", output = "http://tempuri.org/IAdminService/GetOrderPdfLinkResponse")
    @RequestWrapper(localName = "GetOrderPdfLink", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderPdfLink")
    @WebMethod(operationName = "GetOrderPdfLink", action = "http://tempuri.org/IAdminService/GetOrderPdfLink")
    @ResponseWrapper(localName = "GetOrderPdfLinkResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderPdfLinkResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.PdfLinkResponse getOrderPdfLink(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetOrderPdfLinkRequest request
    );

    @WebResult(name = "GetInvoiceReportResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoiceReport", output = "http://tempuri.org/IAdminService/GetInvoiceReportResponse")
    @RequestWrapper(localName = "GetInvoiceReport", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoiceReport")
    @WebMethod(operationName = "GetInvoiceReport", action = "http://tempuri.org/IAdminService/GetInvoiceReport")
    @ResponseWrapper(localName = "GetInvoiceReportResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoiceReportResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceReportResponse getInvoiceReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceReportRequest request
    );

    @WebResult(name = "GetSumOfPaymentPlanAmountResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmount", output = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmountResponse")
    @RequestWrapper(localName = "GetSumOfPaymentPlanAmount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSumOfPaymentPlanAmount")
    @WebMethod(operationName = "GetSumOfPaymentPlanAmount", action = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmount")
    @ResponseWrapper(localName = "GetSumOfPaymentPlanAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSumOfPaymentPlanAmountResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse getSumOfPaymentPlanAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfPaymentPlanAmountRequest request
    );

    @WebResult(name = "GetSumOfInvoiceAmountResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmount", output = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmountResponse")
    @RequestWrapper(localName = "GetSumOfInvoiceAmount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSumOfInvoiceAmount")
    @WebMethod(operationName = "GetSumOfInvoiceAmount", action = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmount")
    @ResponseWrapper(localName = "GetSumOfInvoiceAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSumOfInvoiceAmountResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse getSumOfInvoiceAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfInvoiceAmountRequest request
    );

    @WebResult(name = "UpdateOrderRowsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/UpdateOrderRows", output = "http://tempuri.org/IAdminService/UpdateOrderRowsResponse")
    @RequestWrapper(localName = "UpdateOrderRows", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOrderRows")
    @WebMethod(operationName = "UpdateOrderRows", action = "http://tempuri.org/IAdminService/UpdateOrderRows")
    @ResponseWrapper(localName = "UpdateOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateOrderRowsResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRowsResponse updateOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.UpdateOrderRowsRequest request
    );

    @WebResult(name = "CreditInvoiceRowsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/CreditInvoiceRows", output = "http://tempuri.org/IAdminService/CreditInvoiceRowsResponse")
    @RequestWrapper(localName = "CreditInvoiceRows", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreditInvoiceRows")
    @WebMethod(operationName = "CreditInvoiceRows", action = "http://tempuri.org/IAdminService/CreditInvoiceRows")
    @ResponseWrapper(localName = "CreditInvoiceRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreditInvoiceRowsResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.DeliveryResponse creditInvoiceRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.CreditInvoiceRequest request
    );

    @WebResult(name = "SearchOrdersResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/SearchOrders", output = "http://tempuri.org/IAdminService/SearchOrdersResponse")
    @RequestWrapper(localName = "SearchOrders", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchOrders")
    @WebMethod(operationName = "SearchOrders", action = "http://tempuri.org/IAdminService/SearchOrders")
    @ResponseWrapper(localName = "SearchOrdersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchOrdersResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.SearchOrdersResponse searchOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchOrdersRequest request
    );

    @WebResult(name = "ReleasePendingOrderResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/ReleasePendingOrder", output = "http://tempuri.org/IAdminService/ReleasePendingOrderResponse")
    @RequestWrapper(localName = "ReleasePendingOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReleasePendingOrder")
    @WebMethod(operationName = "ReleasePendingOrder", action = "http://tempuri.org/IAdminService/ReleasePendingOrder")
    @ResponseWrapper(localName = "ReleasePendingOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReleasePendingOrderResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.ReleasePendingResponse releasePendingOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.ReleasePendingRequest request
    );

    @WebResult(name = "GetOrdersResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetOrders", output = "http://tempuri.org/IAdminService/GetOrdersResponse")
    @RequestWrapper(localName = "GetOrders", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrders")
    @WebMethod(operationName = "GetOrders", action = "http://tempuri.org/IAdminService/GetOrders")
    @ResponseWrapper(localName = "GetOrdersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrdersResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetOrdersResponse getOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetOrdersRequest request
    );

    @WebResult(name = "GetSumOfOrderAmountResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfOrderAmount", output = "http://tempuri.org/IAdminService/GetSumOfOrderAmountResponse")
    @RequestWrapper(localName = "GetSumOfOrderAmount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSumOfOrderAmount")
    @WebMethod(operationName = "GetSumOfOrderAmount", action = "http://tempuri.org/IAdminService/GetSumOfOrderAmount")
    @ResponseWrapper(localName = "GetSumOfOrderAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSumOfOrderAmountResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.SumOfAmountResponse getSumOfOrderAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.SumOfOrderAmountRequest request
    );

    @WebResult(name = "CancelOrderRowsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/CancelOrderRows", output = "http://tempuri.org/IAdminService/CancelOrderRowsResponse")
    @RequestWrapper(localName = "CancelOrderRows", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelOrderRows")
    @WebMethod(operationName = "CancelOrderRows", action = "http://tempuri.org/IAdminService/CancelOrderRows")
    @ResponseWrapper(localName = "CancelOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelOrderRowsResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRowsResponse cancelOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.CancelOrderRowsRequest request
    );

    @WebResult(name = "CreateOrderResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/CreateOrder", output = "http://tempuri.org/IAdminService/CreateOrderResponse")
    @RequestWrapper(localName = "CreateOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOrder")
    @WebMethod(operationName = "CreateOrder", action = "http://tempuri.org/IAdminService/CreateOrder")
    @ResponseWrapper(localName = "CreateOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateOrderResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.CreateOrderResponse createOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.CreateOrderRequest request
    );

    @WebResult(name = "GetFinancialReportResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetFinancialReport", output = "http://tempuri.org/IAdminService/GetFinancialReportResponse")
    @RequestWrapper(localName = "GetFinancialReport", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFinancialReport")
    @WebMethod(operationName = "GetFinancialReport", action = "http://tempuri.org/IAdminService/GetFinancialReport")
    @ResponseWrapper(localName = "GetFinancialReportResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFinancialReportResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetFinancialReportResponse getFinancialReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetFinancialReportRequest request
    );

    @WebResult(name = "ChangeInvoiceDueDateResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/ChangeInvoiceDueDate", output = "http://tempuri.org/IAdminService/ChangeInvoiceDueDateResponse")
    @RequestWrapper(localName = "ChangeInvoiceDueDate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeInvoiceDueDate")
    @WebMethod(operationName = "ChangeInvoiceDueDate", action = "http://tempuri.org/IAdminService/ChangeInvoiceDueDate")
    @ResponseWrapper(localName = "ChangeInvoiceDueDateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeInvoiceDueDateResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.ChangeInvoiceDueDateResponse changeInvoiceDueDate(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.ChangeInvoiceDueDateRequest request
    );

    @WebResult(name = "GetInvoicesWithChangedDueDateResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDate", output = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDateResponse")
    @RequestWrapper(localName = "GetInvoicesWithChangedDueDate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoicesWithChangedDueDate")
    @WebMethod(operationName = "GetInvoicesWithChangedDueDate", action = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDate")
    @ResponseWrapper(localName = "GetInvoicesWithChangedDueDateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoicesWithChangedDueDateResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesWithChangedDueDateResponse getInvoicesWithChangedDueDate(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicesWithChangedDueDateRequest request
    );

    @WebResult(name = "SearchInvoicesResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/SearchInvoices", output = "http://tempuri.org/IAdminService/SearchInvoicesResponse")
    @RequestWrapper(localName = "SearchInvoices", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchInvoices")
    @WebMethod(operationName = "SearchInvoices", action = "http://tempuri.org/IAdminService/SearchInvoices")
    @ResponseWrapper(localName = "SearchInvoicesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchInvoicesResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.SearchInvoicesResponse searchInvoices(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchInvoicesRequest request
    );

    @WebResult(name = "GetPaymentPlanReportResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetPaymentPlanReport", output = "http://tempuri.org/IAdminService/GetPaymentPlanReportResponse")
    @RequestWrapper(localName = "GetPaymentPlanReport", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPaymentPlanReport")
    @WebMethod(operationName = "GetPaymentPlanReport", action = "http://tempuri.org/IAdminService/GetPaymentPlanReport")
    @ResponseWrapper(localName = "GetPaymentPlanReportResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPaymentPlanReportResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetPaymentPlanReportResponse getPaymentPlanReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetPaymentPlanReportRequest request
    );

    @WebResult(name = "SearchPaymentPlansResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/SearchPaymentPlans", output = "http://tempuri.org/IAdminService/SearchPaymentPlansResponse")
    @RequestWrapper(localName = "SearchPaymentPlans", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPaymentPlans")
    @WebMethod(operationName = "SearchPaymentPlans", action = "http://tempuri.org/IAdminService/SearchPaymentPlans")
    @ResponseWrapper(localName = "SearchPaymentPlansResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPaymentPlansResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.SearchPaymentPlansResponse searchPaymentPlans(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.SearchPaymentPlansRequest request
    );

    @WebResult(name = "GetInvoiceJournalReportResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoiceJournalReport", output = "http://tempuri.org/IAdminService/GetInvoiceJournalReportResponse")
    @RequestWrapper(localName = "GetInvoiceJournalReport", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoiceJournalReport")
    @WebMethod(operationName = "GetInvoiceJournalReport", action = "http://tempuri.org/IAdminService/GetInvoiceJournalReport")
    @ResponseWrapper(localName = "GetInvoiceJournalReportResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoiceJournalReportResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceJournalReportResponse getInvoiceJournalReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoiceJournalReportRequest request
    );

    @WebResult(name = "ApproveInvoiceResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/ApproveInvoice", output = "http://tempuri.org/IAdminService/ApproveInvoiceResponse")
    @RequestWrapper(localName = "ApproveInvoice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ApproveInvoice")
    @WebMethod(operationName = "ApproveInvoice", action = "http://tempuri.org/IAdminService/ApproveInvoice")
    @ResponseWrapper(localName = "ApproveInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ApproveInvoiceResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.ApproveInvoiceResponse approveInvoice(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.ApproveInvoiceRequest request
    );

    @WebResult(name = "GetInvoicePdfLinkResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicePdfLink", output = "http://tempuri.org/IAdminService/GetInvoicePdfLinkResponse")
    @RequestWrapper(localName = "GetInvoicePdfLink", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoicePdfLink")
    @WebMethod(operationName = "GetInvoicePdfLink", action = "http://tempuri.org/IAdminService/GetInvoicePdfLink")
    @ResponseWrapper(localName = "GetInvoicePdfLinkResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInvoicePdfLinkResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.PdfLinkResponse getInvoicePdfLink(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.GetInvoicePdfLinkRequest request
    );

    @WebResult(name = "AddOrderRowsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IAdminService/AddOrderRows", output = "http://tempuri.org/IAdminService/AddOrderRowsResponse")
    @RequestWrapper(localName = "AddOrderRows", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddOrderRows")
    @WebMethod(operationName = "AddOrderRows", action = "http://tempuri.org/IAdminService/AddOrderRows")
    @ResponseWrapper(localName = "AddOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddOrderRowsResponse")
    public org.datacontract.schemas._2004._07.dataobjects_admin.AddOrderRowsResponse addOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.dataobjects_admin.AddOrderRowsRequest request
    );
}
