package org.notima.api.sveawebpay.adminservice.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-18T13:26:25.721+01:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IAdminService")
@XmlSeeAlso({ObjectFactory.class})
public interface IAdminService {

    @WebMethod(operationName = "GetOrders", action = "http://tempuri.org/IAdminService/GetOrders")
    @Action(input = "http://tempuri.org/IAdminService/GetOrders", output = "http://tempuri.org/IAdminService/GetOrdersResponse")
    @RequestWrapper(localName = "GetOrders", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetOrders")
    @ResponseWrapper(localName = "GetOrdersResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetOrdersResponse")
    @WebResult(name = "GetOrdersResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetOrdersResponse2 getOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetOrdersRequest request
    );

    @WebMethod(operationName = "DeliverPartial", action = "http://tempuri.org/IAdminService/DeliverPartial")
    @Action(input = "http://tempuri.org/IAdminService/DeliverPartial", output = "http://tempuri.org/IAdminService/DeliverPartialResponse")
    @RequestWrapper(localName = "DeliverPartial", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.DeliverPartial")
    @ResponseWrapper(localName = "DeliverPartialResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.DeliverPartialResponse")
    @WebResult(name = "DeliverPartialResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.DeliveryResponse deliverPartial(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.PartialDeliveryRequest request
    );

    @WebMethod(operationName = "GetPaymentPlanReport", action = "http://tempuri.org/IAdminService/GetPaymentPlanReport")
    @Action(input = "http://tempuri.org/IAdminService/GetPaymentPlanReport", output = "http://tempuri.org/IAdminService/GetPaymentPlanReportResponse")
    @RequestWrapper(localName = "GetPaymentPlanReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetPaymentPlanReport")
    @ResponseWrapper(localName = "GetPaymentPlanReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetPaymentPlanReportResponse")
    @WebResult(name = "GetPaymentPlanReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetPaymentPlanReportResponse2 getPaymentPlanReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetPaymentPlanReportRequest request
    );

    @WebMethod(operationName = "GetInvoicesPaidToClientForReport", action = "http://tempuri.org/IAdminService/GetInvoicesPaidToClientForReport")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicesPaidToClientForReport", output = "http://tempuri.org/IAdminService/GetInvoicesPaidToClientForReportResponse")
    @RequestWrapper(localName = "GetInvoicesPaidToClientForReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoicesPaidToClientForReport")
    @ResponseWrapper(localName = "GetInvoicesPaidToClientForReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoicesPaidToClientForReportResponse")
    @WebResult(name = "GetInvoicesPaidToClientForReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetInvoicesPaidToClientForReportResponse2 getInvoicesPaidToClientForReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetInvoicesPaidToClientForReportRequest request
    );

    @WebMethod(operationName = "GetSpecificationReport", action = "http://tempuri.org/IAdminService/GetSpecificationReport")
    @Action(input = "http://tempuri.org/IAdminService/GetSpecificationReport", output = "http://tempuri.org/IAdminService/GetSpecificationReportResponse")
    @RequestWrapper(localName = "GetSpecificationReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetSpecificationReport")
    @ResponseWrapper(localName = "GetSpecificationReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetSpecificationReportResponse")
    @WebResult(name = "GetSpecificationReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetSpecificationReportResponse2 getSpecificationReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetSpecificationReportRequest request
    );

    @WebMethod(operationName = "CreateApprovedOrder", action = "http://tempuri.org/IAdminService/CreateApprovedOrder")
    @Action(input = "http://tempuri.org/IAdminService/CreateApprovedOrder", output = "http://tempuri.org/IAdminService/CreateApprovedOrderResponse")
    @RequestWrapper(localName = "CreateApprovedOrder", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CreateApprovedOrder")
    @ResponseWrapper(localName = "CreateApprovedOrderResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CreateApprovedOrderResponse")
    @WebResult(name = "CreateApprovedOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.CreateApprovedOrderResponse2 createApprovedOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CreateApprovedOrderRequest request
    );

    @WebMethod(operationName = "ChangeInvoiceDueDate", action = "http://tempuri.org/IAdminService/ChangeInvoiceDueDate")
    @Action(input = "http://tempuri.org/IAdminService/ChangeInvoiceDueDate", output = "http://tempuri.org/IAdminService/ChangeInvoiceDueDateResponse")
    @RequestWrapper(localName = "ChangeInvoiceDueDate", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.ChangeInvoiceDueDate")
    @ResponseWrapper(localName = "ChangeInvoiceDueDateResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.ChangeInvoiceDueDateResponse")
    @WebResult(name = "ChangeInvoiceDueDateResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.ChangeInvoiceDueDateResponse2 changeInvoiceDueDate(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.ChangeInvoiceDueDateRequest request
    );

    @WebMethod(operationName = "GetAccountingReport", action = "http://tempuri.org/IAdminService/GetAccountingReport")
    @Action(input = "http://tempuri.org/IAdminService/GetAccountingReport", output = "http://tempuri.org/IAdminService/GetAccountingReportResponse")
    @RequestWrapper(localName = "GetAccountingReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetAccountingReport")
    @ResponseWrapper(localName = "GetAccountingReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetAccountingReportResponse")
    @WebResult(name = "GetAccountingReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetAccountingReportResponse2 getAccountingReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetAccountingReportRequest request
    );

    @WebMethod(operationName = "GenerateAccountCreditRegressReport", action = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReport")
    @Action(input = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReport", output = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReportResponse")
    @RequestWrapper(localName = "GenerateAccountCreditRegressReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GenerateAccountCreditRegressReport")
    @ResponseWrapper(localName = "GenerateAccountCreditRegressReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GenerateAccountCreditRegressReportResponse")
    @WebResult(name = "GenerateAccountCreditRegressReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.AccountCreditRegressReportResponse generateAccountCreditRegressReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.AccountCreditRegressReportRequest request
    );

    @WebMethod(operationName = "CancelPaymentPlanAmount", action = "http://tempuri.org/IAdminService/CancelPaymentPlanAmount")
    @Action(input = "http://tempuri.org/IAdminService/CancelPaymentPlanAmount", output = "http://tempuri.org/IAdminService/CancelPaymentPlanAmountResponse")
    @RequestWrapper(localName = "CancelPaymentPlanAmount", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelPaymentPlanAmount")
    @ResponseWrapper(localName = "CancelPaymentPlanAmountResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelPaymentPlanAmountResponse")
    @WebResult(name = "CancelPaymentPlanAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.CancelPaymentPlanAmountResponse2 cancelPaymentPlanAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CancelPaymentPlanAmountRequest request
    );

    @WebMethod(operationName = "SearchAccountCredits", action = "http://tempuri.org/IAdminService/SearchAccountCredits")
    @Action(input = "http://tempuri.org/IAdminService/SearchAccountCredits", output = "http://tempuri.org/IAdminService/SearchAccountCreditsResponse")
    @RequestWrapper(localName = "SearchAccountCredits", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.SearchAccountCredits")
    @ResponseWrapper(localName = "SearchAccountCreditsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.SearchAccountCreditsResponse")
    @WebResult(name = "SearchAccountCreditsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.SearchAccountCreditsResponse2 searchAccountCredits(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.SearchAccountCreditsRequest request
    );

    @WebMethod(operationName = "GetFinancialReport", action = "http://tempuri.org/IAdminService/GetFinancialReport")
    @Action(input = "http://tempuri.org/IAdminService/GetFinancialReport", output = "http://tempuri.org/IAdminService/GetFinancialReportResponse")
    @RequestWrapper(localName = "GetFinancialReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetFinancialReport")
    @ResponseWrapper(localName = "GetFinancialReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetFinancialReportResponse")
    @WebResult(name = "GetFinancialReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetFinancialReportResponse2 getFinancialReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetFinancialReportRequest request
    );

    @WebMethod(operationName = "GetOrderPdfLink", action = "http://tempuri.org/IAdminService/GetOrderPdfLink")
    @Action(input = "http://tempuri.org/IAdminService/GetOrderPdfLink", output = "http://tempuri.org/IAdminService/GetOrderPdfLinkResponse")
    @RequestWrapper(localName = "GetOrderPdfLink", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetOrderPdfLink")
    @ResponseWrapper(localName = "GetOrderPdfLinkResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetOrderPdfLinkResponse")
    @WebResult(name = "GetOrderPdfLinkResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.PdfLinkResponse getOrderPdfLink(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetOrderPdfLinkRequest request
    );

    @WebMethod(operationName = "GenerateAccountingAgreementType25Report", action = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25Report")
    @Action(input = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25Report", output = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25ReportResponse")
    @RequestWrapper(localName = "GenerateAccountingAgreementType25Report", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GenerateAccountingAgreementType25Report")
    @ResponseWrapper(localName = "GenerateAccountingAgreementType25ReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GenerateAccountingAgreementType25ReportResponse")
    @WebResult(name = "GenerateAccountingAgreementType25ReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.AccountingAgreementType25ReportResponse generateAccountingAgreementType25Report(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.AccountingAgreementType25ReportRequest request
    );

    @WebMethod(operationName = "GetSumOfOrderAmount", action = "http://tempuri.org/IAdminService/GetSumOfOrderAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfOrderAmount", output = "http://tempuri.org/IAdminService/GetSumOfOrderAmountResponse")
    @RequestWrapper(localName = "GetSumOfOrderAmount", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetSumOfOrderAmount")
    @ResponseWrapper(localName = "GetSumOfOrderAmountResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetSumOfOrderAmountResponse")
    @WebResult(name = "GetSumOfOrderAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.SumOfAmountResponse getSumOfOrderAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.SumOfOrderAmountRequest request
    );

    @WebMethod(operationName = "GetInvoiceJournalReport", action = "http://tempuri.org/IAdminService/GetInvoiceJournalReport")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoiceJournalReport", output = "http://tempuri.org/IAdminService/GetInvoiceJournalReportResponse")
    @RequestWrapper(localName = "GetInvoiceJournalReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoiceJournalReport")
    @ResponseWrapper(localName = "GetInvoiceJournalReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoiceJournalReportResponse")
    @WebResult(name = "GetInvoiceJournalReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetInvoiceJournalReportResponse2 getInvoiceJournalReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetInvoiceJournalReportRequest request
    );

    @WebMethod(operationName = "GetInvoicePdfLink", action = "http://tempuri.org/IAdminService/GetInvoicePdfLink")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicePdfLink", output = "http://tempuri.org/IAdminService/GetInvoicePdfLinkResponse")
    @RequestWrapper(localName = "GetInvoicePdfLink", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoicePdfLink")
    @ResponseWrapper(localName = "GetInvoicePdfLinkResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoicePdfLinkResponse")
    @WebResult(name = "GetInvoicePdfLinkResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.PdfLinkResponse getInvoicePdfLink(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetInvoicePdfLinkRequest request
    );

    @WebMethod(operationName = "CancelOrderRows", action = "http://tempuri.org/IAdminService/CancelOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelOrderRows", output = "http://tempuri.org/IAdminService/CancelOrderRowsResponse")
    @RequestWrapper(localName = "CancelOrderRows", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelOrderRows")
    @ResponseWrapper(localName = "CancelOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelOrderRowsResponse")
    @WebResult(name = "CancelOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.CancelOrderRowsResponse2 cancelOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CancelOrderRowsRequest request
    );

    @WebMethod(operationName = "UpdateOrderRows", action = "http://tempuri.org/IAdminService/UpdateOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/UpdateOrderRows", output = "http://tempuri.org/IAdminService/UpdateOrderRowsResponse")
    @RequestWrapper(localName = "UpdateOrderRows", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.UpdateOrderRows")
    @ResponseWrapper(localName = "UpdateOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.UpdateOrderRowsResponse")
    @WebResult(name = "UpdateOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.UpdateOrderRowsResponse2 updateOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.UpdateOrderRowsRequest request
    );

    @WebMethod(operationName = "GetInvoices", action = "http://tempuri.org/IAdminService/GetInvoices")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoices", output = "http://tempuri.org/IAdminService/GetInvoicesResponse")
    @RequestWrapper(localName = "GetInvoices", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoices")
    @ResponseWrapper(localName = "GetInvoicesResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoicesResponse")
    @WebResult(name = "GetInvoicesResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetInvoicesResponse2 getInvoices(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetInvoicesRequest request
    );

    @WebMethod(operationName = "CancelAccountCreditRows", action = "http://tempuri.org/IAdminService/CancelAccountCreditRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelAccountCreditRows", output = "http://tempuri.org/IAdminService/CancelAccountCreditRowsResponse")
    @RequestWrapper(localName = "CancelAccountCreditRows", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelAccountCreditRows")
    @ResponseWrapper(localName = "CancelAccountCreditRowsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelAccountCreditRowsResponse")
    @WebResult(name = "CancelAccountCreditRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.CancelAccountCreditRowsResponse2 cancelAccountCreditRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CancelAccountCreditRowsRequest request
    );

    @WebMethod(operationName = "CreateOrder", action = "http://tempuri.org/IAdminService/CreateOrder")
    @Action(input = "http://tempuri.org/IAdminService/CreateOrder", output = "http://tempuri.org/IAdminService/CreateOrderResponse")
    @RequestWrapper(localName = "CreateOrder", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CreateOrder")
    @ResponseWrapper(localName = "CreateOrderResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CreateOrderResponse")
    @WebResult(name = "CreateOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.CreateOrderResponse2 createOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CreateOrderRequest request
    );

    @WebMethod(operationName = "GetSumOfPaymentPlanAmount", action = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmount", output = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmountResponse")
    @RequestWrapper(localName = "GetSumOfPaymentPlanAmount", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetSumOfPaymentPlanAmount")
    @ResponseWrapper(localName = "GetSumOfPaymentPlanAmountResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetSumOfPaymentPlanAmountResponse")
    @WebResult(name = "GetSumOfPaymentPlanAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.SumOfAmountResponse getSumOfPaymentPlanAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.SumOfPaymentPlanAmountRequest request
    );

    @WebMethod(operationName = "SearchInvoices", action = "http://tempuri.org/IAdminService/SearchInvoices")
    @Action(input = "http://tempuri.org/IAdminService/SearchInvoices", output = "http://tempuri.org/IAdminService/SearchInvoicesResponse")
    @RequestWrapper(localName = "SearchInvoices", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.SearchInvoices")
    @ResponseWrapper(localName = "SearchInvoicesResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.SearchInvoicesResponse")
    @WebResult(name = "SearchInvoicesResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.SearchInvoicesResponse2 searchInvoices(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.SearchInvoicesRequest request
    );

    @WebMethod(operationName = "CancelOrder", action = "http://tempuri.org/IAdminService/CancelOrder")
    @Action(input = "http://tempuri.org/IAdminService/CancelOrder", output = "http://tempuri.org/IAdminService/CancelOrderResponse")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelOrderResponse")
    @WebResult(name = "CancelOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.CancelOrderResponse2 cancelOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CancelOrderRequest request
    );

    @WebMethod(operationName = "ReleasePendingOrder", action = "http://tempuri.org/IAdminService/ReleasePendingOrder")
    @Action(input = "http://tempuri.org/IAdminService/ReleasePendingOrder", output = "http://tempuri.org/IAdminService/ReleasePendingOrderResponse")
    @RequestWrapper(localName = "ReleasePendingOrder", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.ReleasePendingOrder")
    @ResponseWrapper(localName = "ReleasePendingOrderResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.ReleasePendingOrderResponse")
    @WebResult(name = "ReleasePendingOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.ReleasePendingResponse releasePendingOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.ReleasePendingRequest request
    );

    @WebMethod(operationName = "GetInvoiceReport", action = "http://tempuri.org/IAdminService/GetInvoiceReport")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoiceReport", output = "http://tempuri.org/IAdminService/GetInvoiceReportResponse")
    @RequestWrapper(localName = "GetInvoiceReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoiceReport")
    @ResponseWrapper(localName = "GetInvoiceReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoiceReportResponse")
    @WebResult(name = "GetInvoiceReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetInvoiceReportResponse2 getInvoiceReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetInvoiceReportRequest request
    );

    @WebMethod(operationName = "CancelAccountCreditAmount", action = "http://tempuri.org/IAdminService/CancelAccountCreditAmount")
    @Action(input = "http://tempuri.org/IAdminService/CancelAccountCreditAmount", output = "http://tempuri.org/IAdminService/CancelAccountCreditAmountResponse")
    @RequestWrapper(localName = "CancelAccountCreditAmount", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelAccountCreditAmount")
    @ResponseWrapper(localName = "CancelAccountCreditAmountResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelAccountCreditAmountResponse")
    @WebResult(name = "CancelAccountCreditAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.CancelAccountCreditAmountResponse2 cancelAccountCreditAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CancelAccountCreditAmountRequest request
    );

    @WebMethod(operationName = "SearchOrders", action = "http://tempuri.org/IAdminService/SearchOrders")
    @Action(input = "http://tempuri.org/IAdminService/SearchOrders", output = "http://tempuri.org/IAdminService/SearchOrdersResponse")
    @RequestWrapper(localName = "SearchOrders", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.SearchOrders")
    @ResponseWrapper(localName = "SearchOrdersResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.SearchOrdersResponse")
    @WebResult(name = "SearchOrdersResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.SearchOrdersResponse2 searchOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.SearchOrdersRequest request
    );

    @WebMethod(operationName = "SearchPaymentPlans", action = "http://tempuri.org/IAdminService/SearchPaymentPlans")
    @Action(input = "http://tempuri.org/IAdminService/SearchPaymentPlans", output = "http://tempuri.org/IAdminService/SearchPaymentPlansResponse")
    @RequestWrapper(localName = "SearchPaymentPlans", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.SearchPaymentPlans")
    @ResponseWrapper(localName = "SearchPaymentPlansResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.SearchPaymentPlansResponse")
    @WebResult(name = "SearchPaymentPlansResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.SearchPaymentPlansResponse2 searchPaymentPlans(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.SearchPaymentPlansRequest request
    );

    @WebMethod(operationName = "GetOrderEvents", action = "http://tempuri.org/IAdminService/GetOrderEvents")
    @Action(input = "http://tempuri.org/IAdminService/GetOrderEvents", output = "http://tempuri.org/IAdminService/GetOrderEventsResponse")
    @RequestWrapper(localName = "GetOrderEvents", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetOrderEvents")
    @ResponseWrapper(localName = "GetOrderEventsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetOrderEventsResponse")
    @WebResult(name = "GetOrderEventsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetOrderEventsResponse2 getOrderEvents(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetOrderEventsRequest request
    );

    @WebMethod(operationName = "GetDebtInvoicesPaidToClientForReport", action = "http://tempuri.org/IAdminService/GetDebtInvoicesPaidToClientForReport")
    @Action(input = "http://tempuri.org/IAdminService/GetDebtInvoicesPaidToClientForReport", output = "http://tempuri.org/IAdminService/GetDebtInvoicesPaidToClientForReportResponse")
    @RequestWrapper(localName = "GetDebtInvoicesPaidToClientForReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetDebtInvoicesPaidToClientForReport")
    @ResponseWrapper(localName = "GetDebtInvoicesPaidToClientForReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetDebtInvoicesPaidToClientForReportResponse")
    @WebResult(name = "GetDebtInvoicesPaidToClientForReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetDebtInvoicesPaidToClientForReportResponse2 getDebtInvoicesPaidToClientForReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetDebtInvoicesPaidToClientForReportRequest request
    );

    @WebMethod(operationName = "GetAccountCredits", action = "http://tempuri.org/IAdminService/GetAccountCredits")
    @Action(input = "http://tempuri.org/IAdminService/GetAccountCredits", output = "http://tempuri.org/IAdminService/GetAccountCreditsResponse")
    @RequestWrapper(localName = "GetAccountCredits", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetAccountCredits")
    @ResponseWrapper(localName = "GetAccountCreditsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetAccountCreditsResponse")
    @WebResult(name = "GetAccountCreditsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetAccountCreditsResponse2 getAccountCredits(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetAccountCreditsRequest request
    );

    @WebMethod(operationName = "GetClientId", action = "http://tempuri.org/IAdminService/GetClientId")
    @Action(input = "http://tempuri.org/IAdminService/GetClientId", output = "http://tempuri.org/IAdminService/GetClientIdResponse")
    @RequestWrapper(localName = "GetClientId", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetClientId")
    @ResponseWrapper(localName = "GetClientIdResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetClientIdResponse")
    @WebResult(name = "GetClientIdResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetClientIdResponse2 getClientId(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetClientIdRequest request
    );

    @WebMethod(operationName = "GetKickbackReport", action = "http://tempuri.org/IAdminService/GetKickbackReport")
    @Action(input = "http://tempuri.org/IAdminService/GetKickbackReport", output = "http://tempuri.org/IAdminService/GetKickbackReportResponse")
    @RequestWrapper(localName = "GetKickbackReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetKickbackReport")
    @ResponseWrapper(localName = "GetKickbackReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetKickbackReportResponse")
    @WebResult(name = "GetKickbackReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetKickbackReportResponse2 getKickbackReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetKickbackReportRequest request
    );

    @WebMethod(operationName = "CancelPaymentPlanRows", action = "http://tempuri.org/IAdminService/CancelPaymentPlanRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelPaymentPlanRows", output = "http://tempuri.org/IAdminService/CancelPaymentPlanRowsResponse")
    @RequestWrapper(localName = "CancelPaymentPlanRows", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelPaymentPlanRows")
    @ResponseWrapper(localName = "CancelPaymentPlanRowsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CancelPaymentPlanRowsResponse")
    @WebResult(name = "CancelPaymentPlanRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.CancelPaymentPlanRowsResponse2 cancelPaymentPlanRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CancelPaymentPlanRowsRequest request
    );

    @WebMethod(operationName = "ApproveInvoice", action = "http://tempuri.org/IAdminService/ApproveInvoice")
    @Action(input = "http://tempuri.org/IAdminService/ApproveInvoice", output = "http://tempuri.org/IAdminService/ApproveInvoiceResponse")
    @RequestWrapper(localName = "ApproveInvoice", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.ApproveInvoice")
    @ResponseWrapper(localName = "ApproveInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.ApproveInvoiceResponse")
    @WebResult(name = "ApproveInvoiceResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.ApproveInvoiceResponse2 approveInvoice(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.ApproveInvoiceRequest request
    );

    @WebMethod(operationName = "GetInvoicesWithChangedDueDate", action = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDate")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDate", output = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDateResponse")
    @RequestWrapper(localName = "GetInvoicesWithChangedDueDate", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoicesWithChangedDueDate")
    @ResponseWrapper(localName = "GetInvoicesWithChangedDueDateResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetInvoicesWithChangedDueDateResponse")
    @WebResult(name = "GetInvoicesWithChangedDueDateResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetInvoicesWithChangedDueDateResponse2 getInvoicesWithChangedDueDate(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetInvoicesWithChangedDueDateRequest request
    );

    @WebMethod(operationName = "GetClientsByIdentityAccount", action = "http://tempuri.org/IAdminService/GetClientsByIdentityAccount")
    @Action(input = "http://tempuri.org/IAdminService/GetClientsByIdentityAccount", output = "http://tempuri.org/IAdminService/GetClientsByIdentityAccountResponse")
    @RequestWrapper(localName = "GetClientsByIdentityAccount", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetClientsByIdentityAccount")
    @ResponseWrapper(localName = "GetClientsByIdentityAccountResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetClientsByIdentityAccountResponse")
    @WebResult(name = "GetClientsByIdentityAccountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetClientsByIdentityAccountResponse2 getClientsByIdentityAccount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetClientsByIdentityAccountRequest request
    );

    @WebMethod(operationName = "GetSumOfInvoiceAmount", action = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmount", output = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmountResponse")
    @RequestWrapper(localName = "GetSumOfInvoiceAmount", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetSumOfInvoiceAmount")
    @ResponseWrapper(localName = "GetSumOfInvoiceAmountResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetSumOfInvoiceAmountResponse")
    @WebResult(name = "GetSumOfInvoiceAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.SumOfAmountResponse getSumOfInvoiceAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.SumOfInvoiceAmountRequest request
    );

    @WebMethod(operationName = "AddOrderRows", action = "http://tempuri.org/IAdminService/AddOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/AddOrderRows", output = "http://tempuri.org/IAdminService/AddOrderRowsResponse")
    @RequestWrapper(localName = "AddOrderRows", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.AddOrderRows")
    @ResponseWrapper(localName = "AddOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.AddOrderRowsResponse")
    @WebResult(name = "AddOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.AddOrderRowsResponse2 addOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.AddOrderRowsRequest request
    );

    @WebMethod(operationName = "UpdateOrder", action = "http://tempuri.org/IAdminService/UpdateOrder")
    @Action(input = "http://tempuri.org/IAdminService/UpdateOrder", output = "http://tempuri.org/IAdminService/UpdateOrderResponse")
    @RequestWrapper(localName = "UpdateOrder", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.UpdateOrder")
    @ResponseWrapper(localName = "UpdateOrderResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.UpdateOrderResponse")
    @WebResult(name = "UpdateOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.UpdateOrderResponse2 updateOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.UpdateOrderRequest request
    );

    @WebMethod(operationName = "GetRegressionReport", action = "http://tempuri.org/IAdminService/GetRegressionReport")
    @Action(input = "http://tempuri.org/IAdminService/GetRegressionReport", output = "http://tempuri.org/IAdminService/GetRegressionReportResponse")
    @RequestWrapper(localName = "GetRegressionReport", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetRegressionReport")
    @ResponseWrapper(localName = "GetRegressionReportResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetRegressionReportResponse")
    @WebResult(name = "GetRegressionReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetRegressionReportResponse2 getRegressionReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetRegressionReportRequest request
    );

    @WebMethod(operationName = "DeliverOrders", action = "http://tempuri.org/IAdminService/DeliverOrders")
    @Action(input = "http://tempuri.org/IAdminService/DeliverOrders", output = "http://tempuri.org/IAdminService/DeliverOrdersResponse")
    @RequestWrapper(localName = "DeliverOrders", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.DeliverOrders")
    @ResponseWrapper(localName = "DeliverOrdersResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.DeliverOrdersResponse")
    @WebResult(name = "DeliverOrdersResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.DeliveryResponse deliverOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.DeliveryRequest request
    );

    @WebMethod(operationName = "GetPendingReasons", action = "http://tempuri.org/IAdminService/GetPendingReasons")
    @Action(input = "http://tempuri.org/IAdminService/GetPendingReasons", output = "http://tempuri.org/IAdminService/GetPendingReasonsResponse")
    @RequestWrapper(localName = "GetPendingReasons", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetPendingReasons")
    @ResponseWrapper(localName = "GetPendingReasonsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.GetPendingReasonsResponse")
    @WebResult(name = "GetPendingReasonsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.GetPendingReasonsResponse2 getPendingReasons(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.GetPendingReasonsRequest request
    );

    @WebMethod(operationName = "CreditInvoiceRows", action = "http://tempuri.org/IAdminService/CreditInvoiceRows")
    @Action(input = "http://tempuri.org/IAdminService/CreditInvoiceRows", output = "http://tempuri.org/IAdminService/CreditInvoiceRowsResponse")
    @RequestWrapper(localName = "CreditInvoiceRows", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CreditInvoiceRows")
    @ResponseWrapper(localName = "CreditInvoiceRowsResponse", targetNamespace = "http://tempuri.org/", className = "se.sveaekonomi.partnerweb.CreditInvoiceRowsResponse")
    @WebResult(name = "CreditInvoiceRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.api.sveawebpay.adminservice.soap.DeliveryResponse creditInvoiceRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.api.sveawebpay.adminservice.soap.CreditInvoiceRequest request
    );
}
