package org.notima.sveawebpayadmin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-19T14:22:14.705+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IAdminService")
@XmlSeeAlso({ObjectFactory.class})
public interface IAdminService {

    @WebMethod(operationName = "GetOrders", action = "http://tempuri.org/IAdminService/GetOrders")
    @Action(input = "http://tempuri.org/IAdminService/GetOrders", output = "http://tempuri.org/IAdminService/GetOrdersResponse")
    @RequestWrapper(localName = "GetOrders", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetOrders")
    @ResponseWrapper(localName = "GetOrdersResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetOrdersResponse")
    @WebResult(name = "GetOrdersResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetOrdersResponse2 getOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetOrdersRequest request
    );

    @WebMethod(operationName = "DeliverPartial", action = "http://tempuri.org/IAdminService/DeliverPartial")
    @Action(input = "http://tempuri.org/IAdminService/DeliverPartial", output = "http://tempuri.org/IAdminService/DeliverPartialResponse")
    @RequestWrapper(localName = "DeliverPartial", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.DeliverPartial")
    @ResponseWrapper(localName = "DeliverPartialResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.DeliverPartialResponse")
    @WebResult(name = "DeliverPartialResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.DeliveryResponse deliverPartial(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.PartialDeliveryRequest request
    );

    @WebMethod(operationName = "GetPaymentPlanReport", action = "http://tempuri.org/IAdminService/GetPaymentPlanReport")
    @Action(input = "http://tempuri.org/IAdminService/GetPaymentPlanReport", output = "http://tempuri.org/IAdminService/GetPaymentPlanReportResponse")
    @RequestWrapper(localName = "GetPaymentPlanReport", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetPaymentPlanReport")
    @ResponseWrapper(localName = "GetPaymentPlanReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetPaymentPlanReportResponse")
    @WebResult(name = "GetPaymentPlanReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetPaymentPlanReportResponse2 getPaymentPlanReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetPaymentPlanReportRequest request
    );

    @WebMethod(operationName = "GetSpecificationReport", action = "http://tempuri.org/IAdminService/GetSpecificationReport")
    @Action(input = "http://tempuri.org/IAdminService/GetSpecificationReport", output = "http://tempuri.org/IAdminService/GetSpecificationReportResponse")
    @RequestWrapper(localName = "GetSpecificationReport", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetSpecificationReport")
    @ResponseWrapper(localName = "GetSpecificationReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetSpecificationReportResponse")
    @WebResult(name = "GetSpecificationReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetSpecificationReportResponse2 getSpecificationReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetSpecificationReportRequest request
    );

    @WebMethod(operationName = "CreateApprovedOrder", action = "http://tempuri.org/IAdminService/CreateApprovedOrder")
    @Action(input = "http://tempuri.org/IAdminService/CreateApprovedOrder", output = "http://tempuri.org/IAdminService/CreateApprovedOrderResponse")
    @RequestWrapper(localName = "CreateApprovedOrder", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CreateApprovedOrder")
    @ResponseWrapper(localName = "CreateApprovedOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CreateApprovedOrderResponse")
    @WebResult(name = "CreateApprovedOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.CreateApprovedOrderResponse2 createApprovedOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CreateApprovedOrderRequest request
    );

    @WebMethod(operationName = "ChangeInvoiceDueDate", action = "http://tempuri.org/IAdminService/ChangeInvoiceDueDate")
    @Action(input = "http://tempuri.org/IAdminService/ChangeInvoiceDueDate", output = "http://tempuri.org/IAdminService/ChangeInvoiceDueDateResponse")
    @RequestWrapper(localName = "ChangeInvoiceDueDate", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.ChangeInvoiceDueDate")
    @ResponseWrapper(localName = "ChangeInvoiceDueDateResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.ChangeInvoiceDueDateResponse")
    @WebResult(name = "ChangeInvoiceDueDateResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.ChangeInvoiceDueDateResponse2 changeInvoiceDueDate(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.ChangeInvoiceDueDateRequest request
    );

    @WebMethod(operationName = "GetAccountingReport", action = "http://tempuri.org/IAdminService/GetAccountingReport")
    @Action(input = "http://tempuri.org/IAdminService/GetAccountingReport", output = "http://tempuri.org/IAdminService/GetAccountingReportResponse")
    @RequestWrapper(localName = "GetAccountingReport", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetAccountingReport")
    @ResponseWrapper(localName = "GetAccountingReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetAccountingReportResponse")
    @WebResult(name = "GetAccountingReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetAccountingReportResponse2 getAccountingReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetAccountingReportRequest request
    );

    @WebMethod(operationName = "GenerateAccountCreditRegressReport", action = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReport")
    @Action(input = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReport", output = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReportResponse")
    @RequestWrapper(localName = "GenerateAccountCreditRegressReport", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GenerateAccountCreditRegressReport")
    @ResponseWrapper(localName = "GenerateAccountCreditRegressReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GenerateAccountCreditRegressReportResponse")
    @WebResult(name = "GenerateAccountCreditRegressReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.AccountCreditRegressReportResponse generateAccountCreditRegressReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.AccountCreditRegressReportRequest request
    );

    @WebMethod(operationName = "CancelPaymentPlanAmount", action = "http://tempuri.org/IAdminService/CancelPaymentPlanAmount")
    @Action(input = "http://tempuri.org/IAdminService/CancelPaymentPlanAmount", output = "http://tempuri.org/IAdminService/CancelPaymentPlanAmountResponse")
    @RequestWrapper(localName = "CancelPaymentPlanAmount", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelPaymentPlanAmount")
    @ResponseWrapper(localName = "CancelPaymentPlanAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelPaymentPlanAmountResponse")
    @WebResult(name = "CancelPaymentPlanAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.CancelPaymentPlanAmountResponse2 cancelPaymentPlanAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CancelPaymentPlanAmountRequest request
    );

    @WebMethod(operationName = "SearchAccountCredits", action = "http://tempuri.org/IAdminService/SearchAccountCredits")
    @Action(input = "http://tempuri.org/IAdminService/SearchAccountCredits", output = "http://tempuri.org/IAdminService/SearchAccountCreditsResponse")
    @RequestWrapper(localName = "SearchAccountCredits", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.SearchAccountCredits")
    @ResponseWrapper(localName = "SearchAccountCreditsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.SearchAccountCreditsResponse2")
    @WebResult(name = "SearchAccountCreditsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.SearchAccountCreditsResponse searchAccountCredits(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.SearchAccountCreditsRequest request
    );

    @WebMethod(operationName = "GetFinancialReport", action = "http://tempuri.org/IAdminService/GetFinancialReport")
    @Action(input = "http://tempuri.org/IAdminService/GetFinancialReport", output = "http://tempuri.org/IAdminService/GetFinancialReportResponse")
    @RequestWrapper(localName = "GetFinancialReport", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetFinancialReport")
    @ResponseWrapper(localName = "GetFinancialReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetFinancialReportResponse")
    @WebResult(name = "GetFinancialReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetFinancialReportResponse2 getFinancialReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetFinancialReportRequest request
    );

    @WebMethod(operationName = "GetOrderPdfLink", action = "http://tempuri.org/IAdminService/GetOrderPdfLink")
    @Action(input = "http://tempuri.org/IAdminService/GetOrderPdfLink", output = "http://tempuri.org/IAdminService/GetOrderPdfLinkResponse")
    @RequestWrapper(localName = "GetOrderPdfLink", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetOrderPdfLink")
    @ResponseWrapper(localName = "GetOrderPdfLinkResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetOrderPdfLinkResponse")
    @WebResult(name = "GetOrderPdfLinkResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.PdfLinkResponse getOrderPdfLink(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetOrderPdfLinkRequest request
    );

    @WebMethod(operationName = "GenerateAccountingAgreementType25Report", action = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25Report")
    @Action(input = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25Report", output = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25ReportResponse")
    @RequestWrapper(localName = "GenerateAccountingAgreementType25Report", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GenerateAccountingAgreementType25Report")
    @ResponseWrapper(localName = "GenerateAccountingAgreementType25ReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GenerateAccountingAgreementType25ReportResponse")
    @WebResult(name = "GenerateAccountingAgreementType25ReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.AccountingAgreementType25ReportResponse generateAccountingAgreementType25Report(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.AccountingAgreementType25ReportRequest request
    );

    @WebMethod(operationName = "GetSumOfOrderAmount", action = "http://tempuri.org/IAdminService/GetSumOfOrderAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfOrderAmount", output = "http://tempuri.org/IAdminService/GetSumOfOrderAmountResponse")
    @RequestWrapper(localName = "GetSumOfOrderAmount", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetSumOfOrderAmount")
    @ResponseWrapper(localName = "GetSumOfOrderAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetSumOfOrderAmountResponse")
    @WebResult(name = "GetSumOfOrderAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.SumOfAmountResponse getSumOfOrderAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.SumOfOrderAmountRequest request
    );

    @WebMethod(operationName = "GetInvoiceJournalReport", action = "http://tempuri.org/IAdminService/GetInvoiceJournalReport")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoiceJournalReport", output = "http://tempuri.org/IAdminService/GetInvoiceJournalReportResponse")
    @RequestWrapper(localName = "GetInvoiceJournalReport", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoiceJournalReport")
    @ResponseWrapper(localName = "GetInvoiceJournalReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoiceJournalReportResponse")
    @WebResult(name = "GetInvoiceJournalReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetInvoiceJournalReportResponse2 getInvoiceJournalReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetInvoiceJournalReportRequest request
    );

    @WebMethod(operationName = "GetInvoicePdfLink", action = "http://tempuri.org/IAdminService/GetInvoicePdfLink")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicePdfLink", output = "http://tempuri.org/IAdminService/GetInvoicePdfLinkResponse")
    @RequestWrapper(localName = "GetInvoicePdfLink", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoicePdfLink")
    @ResponseWrapper(localName = "GetInvoicePdfLinkResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoicePdfLinkResponse")
    @WebResult(name = "GetInvoicePdfLinkResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.PdfLinkResponse getInvoicePdfLink(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetInvoicePdfLinkRequest request
    );

    @WebMethod(operationName = "CancelOrderRows", action = "http://tempuri.org/IAdminService/CancelOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelOrderRows", output = "http://tempuri.org/IAdminService/CancelOrderRowsResponse")
    @RequestWrapper(localName = "CancelOrderRows", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelOrderRows")
    @ResponseWrapper(localName = "CancelOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelOrderRowsResponse")
    @WebResult(name = "CancelOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.CancelOrderRowsResponse2 cancelOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CancelOrderRowsRequest request
    );

    @WebMethod(operationName = "UpdateOrderRows", action = "http://tempuri.org/IAdminService/UpdateOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/UpdateOrderRows", output = "http://tempuri.org/IAdminService/UpdateOrderRowsResponse")
    @RequestWrapper(localName = "UpdateOrderRows", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.UpdateOrderRows")
    @ResponseWrapper(localName = "UpdateOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.UpdateOrderRowsResponse")
    @WebResult(name = "UpdateOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.UpdateOrderRowsResponse2 updateOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.UpdateOrderRowsRequest request
    );

    @WebMethod(operationName = "GetInvoices", action = "http://tempuri.org/IAdminService/GetInvoices")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoices", output = "http://tempuri.org/IAdminService/GetInvoicesResponse")
    @RequestWrapper(localName = "GetInvoices", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoices")
    @ResponseWrapper(localName = "GetInvoicesResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoicesResponse")
    @WebResult(name = "GetInvoicesResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetInvoicesResponse2 getInvoices(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetInvoicesRequest request
    );

    @WebMethod(operationName = "CancelAccountCreditRows", action = "http://tempuri.org/IAdminService/CancelAccountCreditRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelAccountCreditRows", output = "http://tempuri.org/IAdminService/CancelAccountCreditRowsResponse")
    @RequestWrapper(localName = "CancelAccountCreditRows", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelAccountCreditRows")
    @ResponseWrapper(localName = "CancelAccountCreditRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelAccountCreditRowsResponse2")
    @WebResult(name = "CancelAccountCreditRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.CancelAccountCreditRowsResponse cancelAccountCreditRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CancelAccountCreditRowsRequest request
    );

    @WebMethod(operationName = "CreateOrder", action = "http://tempuri.org/IAdminService/CreateOrder")
    @Action(input = "http://tempuri.org/IAdminService/CreateOrder", output = "http://tempuri.org/IAdminService/CreateOrderResponse")
    @RequestWrapper(localName = "CreateOrder", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CreateOrder")
    @ResponseWrapper(localName = "CreateOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CreateOrderResponse")
    @WebResult(name = "CreateOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.CreateOrderResponse2 createOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CreateOrderRequest request
    );

    @WebMethod(operationName = "GetSumOfPaymentPlanAmount", action = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmount", output = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmountResponse")
    @RequestWrapper(localName = "GetSumOfPaymentPlanAmount", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetSumOfPaymentPlanAmount")
    @ResponseWrapper(localName = "GetSumOfPaymentPlanAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetSumOfPaymentPlanAmountResponse")
    @WebResult(name = "GetSumOfPaymentPlanAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.SumOfAmountResponse getSumOfPaymentPlanAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.SumOfPaymentPlanAmountRequest request
    );

    @WebMethod(operationName = "SearchInvoices", action = "http://tempuri.org/IAdminService/SearchInvoices")
    @Action(input = "http://tempuri.org/IAdminService/SearchInvoices", output = "http://tempuri.org/IAdminService/SearchInvoicesResponse")
    @RequestWrapper(localName = "SearchInvoices", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.SearchInvoices")
    @ResponseWrapper(localName = "SearchInvoicesResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.SearchInvoicesResponse")
    @WebResult(name = "SearchInvoicesResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.SearchInvoicesResponse2 searchInvoices(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.SearchInvoicesRequest request
    );

    @WebMethod(operationName = "CancelOrder", action = "http://tempuri.org/IAdminService/CancelOrder")
    @Action(input = "http://tempuri.org/IAdminService/CancelOrder", output = "http://tempuri.org/IAdminService/CancelOrderResponse")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelOrderResponse")
    @WebResult(name = "CancelOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.CancelOrderResponse2 cancelOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CancelOrderRequest request
    );

    @WebMethod(operationName = "ReleasePendingOrder", action = "http://tempuri.org/IAdminService/ReleasePendingOrder")
    @Action(input = "http://tempuri.org/IAdminService/ReleasePendingOrder", output = "http://tempuri.org/IAdminService/ReleasePendingOrderResponse")
    @RequestWrapper(localName = "ReleasePendingOrder", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.ReleasePendingOrder")
    @ResponseWrapper(localName = "ReleasePendingOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.ReleasePendingOrderResponse")
    @WebResult(name = "ReleasePendingOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.ReleasePendingResponse releasePendingOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.ReleasePendingRequest request
    );

    @WebMethod(operationName = "GetInvoiceReport", action = "http://tempuri.org/IAdminService/GetInvoiceReport")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoiceReport", output = "http://tempuri.org/IAdminService/GetInvoiceReportResponse")
    @RequestWrapper(localName = "GetInvoiceReport", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoiceReport")
    @ResponseWrapper(localName = "GetInvoiceReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoiceReportResponse")
    @WebResult(name = "GetInvoiceReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetInvoiceReportResponse2 getInvoiceReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetInvoiceReportRequest request
    );

    @WebMethod(operationName = "CancelAccountCreditAmount", action = "http://tempuri.org/IAdminService/CancelAccountCreditAmount")
    @Action(input = "http://tempuri.org/IAdminService/CancelAccountCreditAmount", output = "http://tempuri.org/IAdminService/CancelAccountCreditAmountResponse")
    @RequestWrapper(localName = "CancelAccountCreditAmount", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelAccountCreditAmount")
    @ResponseWrapper(localName = "CancelAccountCreditAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelAccountCreditAmountResponse2")
    @WebResult(name = "CancelAccountCreditAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.CancelAccountCreditAmountResponse cancelAccountCreditAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CancelAccountCreditAmountRequest request
    );

    @WebMethod(operationName = "SearchOrders", action = "http://tempuri.org/IAdminService/SearchOrders")
    @Action(input = "http://tempuri.org/IAdminService/SearchOrders", output = "http://tempuri.org/IAdminService/SearchOrdersResponse")
    @RequestWrapper(localName = "SearchOrders", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.SearchOrders")
    @ResponseWrapper(localName = "SearchOrdersResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.SearchOrdersResponse")
    @WebResult(name = "SearchOrdersResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.SearchOrdersResponse2 searchOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.SearchOrdersRequest request
    );

    @WebMethod(operationName = "SearchPaymentPlans", action = "http://tempuri.org/IAdminService/SearchPaymentPlans")
    @Action(input = "http://tempuri.org/IAdminService/SearchPaymentPlans", output = "http://tempuri.org/IAdminService/SearchPaymentPlansResponse")
    @RequestWrapper(localName = "SearchPaymentPlans", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.SearchPaymentPlans")
    @ResponseWrapper(localName = "SearchPaymentPlansResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.SearchPaymentPlansResponse")
    @WebResult(name = "SearchPaymentPlansResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.SearchPaymentPlansResponse2 searchPaymentPlans(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.SearchPaymentPlansRequest request
    );

    @WebMethod(operationName = "GetOrderEvents", action = "http://tempuri.org/IAdminService/GetOrderEvents")
    @Action(input = "http://tempuri.org/IAdminService/GetOrderEvents", output = "http://tempuri.org/IAdminService/GetOrderEventsResponse")
    @RequestWrapper(localName = "GetOrderEvents", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetOrderEvents")
    @ResponseWrapper(localName = "GetOrderEventsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetOrderEventsResponse")
    @WebResult(name = "GetOrderEventsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetOrderEventsResponse2 getOrderEvents(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetOrderEventsRequest request
    );

    @WebMethod(operationName = "GetAccountCredits", action = "http://tempuri.org/IAdminService/GetAccountCredits")
    @Action(input = "http://tempuri.org/IAdminService/GetAccountCredits", output = "http://tempuri.org/IAdminService/GetAccountCreditsResponse")
    @RequestWrapper(localName = "GetAccountCredits", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetAccountCredits")
    @ResponseWrapper(localName = "GetAccountCreditsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetAccountCreditsResponse2")
    @WebResult(name = "GetAccountCreditsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetAccountCreditsResponse getAccountCredits(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetAccountCreditsRequest request
    );

    @WebMethod(operationName = "GetClientId", action = "http://tempuri.org/IAdminService/GetClientId")
    @Action(input = "http://tempuri.org/IAdminService/GetClientId", output = "http://tempuri.org/IAdminService/GetClientIdResponse")
    @RequestWrapper(localName = "GetClientId", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetClientId")
    @ResponseWrapper(localName = "GetClientIdResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetClientIdResponse2")
    @WebResult(name = "GetClientIdResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetClientIdResponse getClientId(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetClientIdRequest request
    );

    @WebMethod(operationName = "CancelPaymentPlanRows", action = "http://tempuri.org/IAdminService/CancelPaymentPlanRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelPaymentPlanRows", output = "http://tempuri.org/IAdminService/CancelPaymentPlanRowsResponse")
    @RequestWrapper(localName = "CancelPaymentPlanRows", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelPaymentPlanRows")
    @ResponseWrapper(localName = "CancelPaymentPlanRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CancelPaymentPlanRowsResponse")
    @WebResult(name = "CancelPaymentPlanRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.CancelPaymentPlanRowsResponse2 cancelPaymentPlanRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CancelPaymentPlanRowsRequest request
    );

    @WebMethod(operationName = "ApproveInvoice", action = "http://tempuri.org/IAdminService/ApproveInvoice")
    @Action(input = "http://tempuri.org/IAdminService/ApproveInvoice", output = "http://tempuri.org/IAdminService/ApproveInvoiceResponse")
    @RequestWrapper(localName = "ApproveInvoice", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.ApproveInvoice")
    @ResponseWrapper(localName = "ApproveInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.ApproveInvoiceResponse")
    @WebResult(name = "ApproveInvoiceResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.ApproveInvoiceResponse2 approveInvoice(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.ApproveInvoiceRequest request
    );

    @WebMethod(operationName = "GetInvoicesWithChangedDueDate", action = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDate")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDate", output = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDateResponse")
    @RequestWrapper(localName = "GetInvoicesWithChangedDueDate", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoicesWithChangedDueDate")
    @ResponseWrapper(localName = "GetInvoicesWithChangedDueDateResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetInvoicesWithChangedDueDateResponse")
    @WebResult(name = "GetInvoicesWithChangedDueDateResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetInvoicesWithChangedDueDateResponse2 getInvoicesWithChangedDueDate(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetInvoicesWithChangedDueDateRequest request
    );

    @WebMethod(operationName = "GetClientsByIdentityAccount", action = "http://tempuri.org/IAdminService/GetClientsByIdentityAccount")
    @Action(input = "http://tempuri.org/IAdminService/GetClientsByIdentityAccount", output = "http://tempuri.org/IAdminService/GetClientsByIdentityAccountResponse")
    @RequestWrapper(localName = "GetClientsByIdentityAccount", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetClientsByIdentityAccount")
    @ResponseWrapper(localName = "GetClientsByIdentityAccountResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetClientsByIdentityAccountResponse2")
    @WebResult(name = "GetClientsByIdentityAccountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetClientsByIdentityAccountResponse getClientsByIdentityAccount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetClientsByIdentityAccountRequest request
    );

    @WebMethod(operationName = "GetSumOfInvoiceAmount", action = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmount", output = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmountResponse")
    @RequestWrapper(localName = "GetSumOfInvoiceAmount", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetSumOfInvoiceAmount")
    @ResponseWrapper(localName = "GetSumOfInvoiceAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetSumOfInvoiceAmountResponse")
    @WebResult(name = "GetSumOfInvoiceAmountResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.SumOfAmountResponse getSumOfInvoiceAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.SumOfInvoiceAmountRequest request
    );

    @WebMethod(operationName = "AddOrderRows", action = "http://tempuri.org/IAdminService/AddOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/AddOrderRows", output = "http://tempuri.org/IAdminService/AddOrderRowsResponse")
    @RequestWrapper(localName = "AddOrderRows", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.AddOrderRows")
    @ResponseWrapper(localName = "AddOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.AddOrderRowsResponse")
    @WebResult(name = "AddOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.AddOrderRowsResponse2 addOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.AddOrderRowsRequest request
    );

    @WebMethod(operationName = "UpdateOrder", action = "http://tempuri.org/IAdminService/UpdateOrder")
    @Action(input = "http://tempuri.org/IAdminService/UpdateOrder", output = "http://tempuri.org/IAdminService/UpdateOrderResponse")
    @RequestWrapper(localName = "UpdateOrder", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.UpdateOrder")
    @ResponseWrapper(localName = "UpdateOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.UpdateOrderResponse")
    @WebResult(name = "UpdateOrderResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.UpdateOrderResponse2 updateOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.UpdateOrderRequest request
    );

    @WebMethod(operationName = "GetRegressionReport", action = "http://tempuri.org/IAdminService/GetRegressionReport")
    @Action(input = "http://tempuri.org/IAdminService/GetRegressionReport", output = "http://tempuri.org/IAdminService/GetRegressionReportResponse")
    @RequestWrapper(localName = "GetRegressionReport", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetRegressionReport")
    @ResponseWrapper(localName = "GetRegressionReportResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetRegressionReportResponse")
    @WebResult(name = "GetRegressionReportResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetRegressionReportResponse2 getRegressionReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetRegressionReportRequest request
    );

    @WebMethod(operationName = "DeliverOrders", action = "http://tempuri.org/IAdminService/DeliverOrders")
    @Action(input = "http://tempuri.org/IAdminService/DeliverOrders", output = "http://tempuri.org/IAdminService/DeliverOrdersResponse")
    @RequestWrapper(localName = "DeliverOrders", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.DeliverOrders")
    @ResponseWrapper(localName = "DeliverOrdersResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.DeliverOrdersResponse")
    @WebResult(name = "DeliverOrdersResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.DeliveryResponse deliverOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.DeliveryRequest request
    );

    @WebMethod(operationName = "GetPendingReasons", action = "http://tempuri.org/IAdminService/GetPendingReasons")
    @Action(input = "http://tempuri.org/IAdminService/GetPendingReasons", output = "http://tempuri.org/IAdminService/GetPendingReasonsResponse")
    @RequestWrapper(localName = "GetPendingReasons", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetPendingReasons")
    @ResponseWrapper(localName = "GetPendingReasonsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.GetPendingReasonsResponse2")
    @WebResult(name = "GetPendingReasonsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.GetPendingReasonsResponse getPendingReasons(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.GetPendingReasonsRequest request
    );

    @WebMethod(operationName = "CreditInvoiceRows", action = "http://tempuri.org/IAdminService/CreditInvoiceRows")
    @Action(input = "http://tempuri.org/IAdminService/CreditInvoiceRows", output = "http://tempuri.org/IAdminService/CreditInvoiceRowsResponse")
    @RequestWrapper(localName = "CreditInvoiceRows", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CreditInvoiceRows")
    @ResponseWrapper(localName = "CreditInvoiceRowsResponse", targetNamespace = "http://tempuri.org/", className = "org.notima.sveawebpayadmin.CreditInvoiceRowsResponse")
    @WebResult(name = "CreditInvoiceRowsResult", targetNamespace = "http://tempuri.org/")
    public org.notima.sveawebpayadmin.DeliveryResponse creditInvoiceRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.notima.sveawebpayadmin.CreditInvoiceRequest request
    );
}
